/* eslint-disable @typescript-eslint/ban-ts-comment */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useEffect } from 'react'
import * as THREE from 'three'
import { GroupProps, useFrame } from '@react-three/fiber'

export type { GroupProps as Props }

const Persona = (props: GroupProps) => {
  const group = useRef<THREE.Group>(null)
  const mixer = useRef<THREE.AnimationMixer>()
  const { nodes, materials, animations } = useGLTF('/dancing.glb')

  useEffect(() => {
    if (group.current && animations.length) {
      mixer.current = new THREE.AnimationMixer(group.current)
      animations.forEach((clip) => {
        const action = mixer.current?.clipAction?.(clip)
        action?.play?.()
      })
    }
  })

  useFrame((_state, delta) => {
    mixer.current?.update?.(delta)
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature">
          <primitive object={nodes.Hips} />
          <skinnedMesh
            name="Wolf3D_Body"
            // @ts-ignore
            geometry={nodes.Wolf3D_Body.geometry}
            material={materials.Wolf3D_Body}
            // @ts-ignore
            skeleton={nodes.Wolf3D_Body.skeleton}
          />
          <skinnedMesh
            name="Wolf3D_Glasses"
            // @ts-ignore
            geometry={nodes.Wolf3D_Glasses.geometry}
            material={materials.Wolf3D_Glasses}
            // @ts-ignore
            skeleton={nodes.Wolf3D_Glasses.skeleton}
          />
          <skinnedMesh
            name="Wolf3D_Hair"
            // @ts-ignore
            geometry={nodes.Wolf3D_Hair.geometry}
            material={materials.Wolf3D_Hair}
            // @ts-ignore
            skeleton={nodes.Wolf3D_Hair.skeleton}
          />
          <skinnedMesh
            name="Wolf3D_Outfit_Bottom"
            // @ts-ignore
            geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
            material={materials.Wolf3D_Outfit_Bottom}
            // @ts-ignore
            skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
          />
          <skinnedMesh
            name="Wolf3D_Outfit_Footwear"
            // @ts-ignore
            geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
            material={materials.Wolf3D_Outfit_Footwear}
            // @ts-ignore
            skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
          />
          <skinnedMesh
            name="Wolf3D_Outfit_Top"
            // @ts-ignore
            geometry={nodes.Wolf3D_Outfit_Top.geometry}
            material={materials.Wolf3D_Outfit_Top}
            // @ts-ignore
            skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
          />
          <skinnedMesh
            name="EyeLeft"
            // @ts-ignore
            geometry={nodes.EyeLeft.geometry}
            material={materials.Wolf3D_Eye}
            // @ts-ignore
            skeleton={nodes.EyeLeft.skeleton}
            // @ts-ignore
            morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
            // @ts-ignore
            morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
          />
          <skinnedMesh
            name="EyeRight"
            // @ts-ignore
            geometry={nodes.EyeRight.geometry}
            material={materials.Wolf3D_Eye}
            // @ts-ignore
            skeleton={nodes.EyeRight.skeleton}
            // @ts-ignore
            morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
            // @ts-ignore
            morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
          />
          <skinnedMesh
            name="Wolf3D_Head"
            // @ts-ignore
            geometry={nodes.Wolf3D_Head.geometry}
            material={materials.Wolf3D_Skin}
            // @ts-ignore
            skeleton={nodes.Wolf3D_Head.skeleton}
            // @ts-ignore
            morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
            // @ts-ignore
            morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
          />
          <skinnedMesh
            name="Wolf3D_Teeth"
            // @ts-ignore
            geometry={nodes.Wolf3D_Teeth.geometry}
            material={materials.Wolf3D_Teeth}
            // @ts-ignore
            skeleton={nodes.Wolf3D_Teeth.skeleton}
            // @ts-ignore
            morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
            // @ts-ignore
            morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/dancing.glb')

export default Persona
