name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'workspaces/**'

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '20.18.1'
          cache: 'yarn'

      - name: Install xvfb (Virtual Display) # puppeteer needs that
        run: sudo apt-get install -y xvfb

      - name: Install packages
        run: yarn install


      - name: Generate opengraph & resume
        run: yarn generate

      - name: Build
        run: yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./workspaces/website/out
